project:
  type: website

website:
  title: "GIS4Epidemiology"
  description: "Homepage for GIS4EPI - Workshop at Central University Gujarat (CUG), 28th May 2024."
  favicon: "images/logo.png"
  site-url: "https://drarunmitra.github.io/GIS4Epidemiology/"
  page-navigation: true
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, Arun Mitra"
    
  navbar:
    left:
      - text: Home
        href: index.qmd
        
      - text: Session One
        menu:
          - text: Concepts in Spatial Epidemilogy
            href: session1a-foundational-concepts.qmd
          - text: Introduction to Spatial Data Science
            href: session1b-intro-sds.qmd
          - text: Spatial Data Analysis
            href: session1c-investigate-outbreak.qmd
            
      - text: Session Two
        menu:
          - text: Spatial Data Visualization
            href: session2a-spatial-data-vis.qmd
          - text: Case Studies
            href: session2b-case-studies.qmd
          - text: Exercises    
            href: session2c-hands-on.qmd
            
      - text: About
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap



