---
title: "GIS for Epidemiology"
subtitle: "Day 2 of **Geospatial Technology for Public Health Policy** Workshop <br>*May 27--29, 2024 --- GISE Hub, IIT Bombay<br>\\@Central University Gujarat (CUG), Gandhinagar*" 
date: "May 28, 2024"

author:
  - name: Prof. (Dr.) Biju Soman
    affiliations:
      - ref: sctimst
  - name: Dr. Arun Mitra
    affiliations:
      - ref: aiims
affiliations:
  - id: sctimst
    name: Sree Chitra Tirunal Institute for Medical Sciences and Technology (SCTIMST), Trivandrum
    city: Trivandrum
    state: KL
  - id: aiims
    name: All India Intstitute of Medical Sciences (AIIMS), Bibinagar, Hyderabad
    city: Bibinagar, Hyderabad
    state: TS
    
format: 
  html: default
  revealjs: 
    output-file: slides-index.html
  pdf: default
---

# Welcome

  - Welcome to the Day 2 of **Geospatial Technology for Public Health Policy** Workshop!
  - The goal for today is to highlight the applications of GIS in Epidemiology while providing the foundational concepts in Spatial Epidemiology. 
  - The workshop introduces the participants to the field of Spatial Data Science through the statistical programming language R.
  - The workshop is intended as an introductory window into the world of spatial data analysis and visualization for public health policy.
  - Workshop materials in the github repository [GIS4EPI-Workshop](https://github.com/drarunmitra/GIS4Epidemiology)

## Learning Objectives for Tutorial

At the end of the day, participants will be able to:

  - Identify the main features that make Julia an attractive language for Data Science
  - Set up a Julia environment to run their data analysis
  - Efficiently handle datasets (even across different languages) through Tables.jl and Arrow.jl
  - Fit (generalized) linear mixed models with MixedModels.jl
  - Communicate across languages (Julia, R, python)



# Schedule

| Time          | Session       |  Topic                                                                                           | 
|:-------------:|:-------------:|:-------------------------------------------------------------------------------------------------|
| 10:00 - 10:50 | Session1a       | [Foundational Concepts in Spatial Epidemiology](session1a-foundational-concepts.qmd)  | 
|               | |: _Bio-Break_                                                                                      :| 
| 11:00 - 11:50 | Session 1b | [Introduction to Spatial Data Science using R](session1b-intro-sds.qmd)               |
|               | | _Bio-Break_                                                                                      | 
| 12:00 - 12:50 | Session 1c | [Investigating an Outbreak: Applications of Spatial Epidemiology](session1c-investigate-outbreak.qmd) | 
|               | | _Lunch_                                                                                          | 
| 14:00 - 14:50 | Session 2a | [Spatial Data Visualization: Principles and Best Practices](session2a-spatial-data-vis.qmd) | 
|               | | _Bio-Break_                                                                                      | 
| 15:00 - 15:50 | Session 2b | [Case Studies: Spatial Data Analysis and Visualization](session2b-case-studies.qmd) | 
|               | | _Bio-Break_                                                                                      | 
| 16:00 - 16:50 | Session 2c | [Hands-on Exercises](session2c-hands-on.qmd) | 
| 16:50 - 17:00 | | _Q&A Session_              |  

# In preparation for the workshop

Participants are required to follow the next steps before the day of the workshop:

 1. Install R

 2. Install RStudio. 
 
 3. Install packages 

  - tidyverse: `install.packages('tidyverse')`
  - sf: `install.packages('sf')`
  - rgeoda: `install.packages('rgeoda')`
  - tidyverse: `install.packages('tidyverse')`
  - leaflet: `install.packages('leaflet')`
  - here: `install.packages('here')`